name: lint

on:
  push:
    paths:
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.17.x"
      - name: Run gofmt
        run: test -z $(gofmt -l .)
      - name: Run go vet
        run: go vet ./...
      - name: Run golint
        run: |
          go get golang.org/x/lint/golint
          export PATH=$PATH:$(go env GOPATH)/bin
          golint -set_exit_status ./...
